# Generated by Django 5.2 on 2025-05-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_topic_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='host',
        ),
    ]
